
source:
  csv: C:\Users\andre\Desktop\the_real_thing\Participants_complete.csv
  separator: ';'
  columns:
    - name: name
    - last name: last name
    - email: email
    - track: track

output:
  csv: C:\Users\andre\Desktop\the_real_thing\responses-out.csv
  separator: ';'

tracks:
  AI:
    - AI
    - Artificial Intelligence
    - A Intelligence
    - Artificial I
  WebDev:
    - webdev
    - Web Development
    - Frontend
    - Backend
    - Web
    - web dev
  UX:
    - ux
    - user experience
    - uxperience
    - user x
    - UX Design
  DataSc:
    - Data Science
    - dsc
    - Data

fuzzy:
  certainty ratio: 91
